Repository friends-of-presta/fop_console, pull requests merged in 2021-10, with the labels that each got.

#108 New Command to setup developement environnement from dev branch
  README.md
  config/services.yml
  src/Commands/DevSetupEnv.php
Labels: feature

#156 New Release Drafter
  .github/release-drafter.yml
  .github/release-drafter_config.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release_module.yml
Labels: enhancement

#201 Details on php cs fixer failure - fixes #198
  .github/workflows/php-cs-fixer.yml
Labels: dev
