Repository friends-of-presta/fop_console, pull requests merged in 2021-06, with the labels that each got.

#124 Fix currency precision
  src/Context/ConsoleLoader.php
Labels: bug

#129 Phpstan level5
  .devtools/phpstan_baseline.neon
  composer.json
  composer.lock
  phpstan.neon.dist
  src/Commands/MakeOverride.php
  src/Commands/ModuleHooks.php
  src/Context/ConsoleLoader.php
Labels: enhancement

#131 Contributors
  CONTRIBUTORS.md
Labels: documentation

#130 Fix php stan level 5
  .devtools/phpstan_baseline.neon
  src/Commands/Export.php
  src/Commands/GenerateHtaccess.php
  src/Commands/GenerateRobots.php
  src/Commands/HookModule.php
  src/Commands/Images/GenerateAbstract.php
  src/Commands/LatestProducts.php
  src/Commands/ShopStatus.php
  src/Commands/ThemeResetLayout.php
  src/Commands/UnhookModule.php
  src/Context/ConsoleLoader.php
Labels: enhancement

#137 Fix errors PHPStan level 5
  .devtools/phpstan_baseline.neon
  src/Commands/DebugMode.php
  src/Commands/Maintenance.php
Labels: enhancement

#138 Fix some errors phpstan
  .devtools/phpstan_baseline.neon
  src/Commands/Customers/CustomersGroups.php
Labels: enhancement
