Repository friends-of-presta/fop_console, pull requests merged in 2021-09, with the labels that each got.

#164 chore: add missing theme's reset command
  README.md
Labels: documentation

#154 Add RenameModule command
  README.md
  composer.lock
  config/services.yml
  src/Commands/Modules/HookModule.php
  src/Commands/Modules/ModuleHooks.php
  src/Commands/Modules/RenameModule.php
  src/Commands/Modules/UnhookModule.php
Labels: feature

#162 62 validate hook name
  src/Commands/AddHook.php
Labels: enhancement

#149 fix #147 - grumphp first run : const FOP_PHPSTAN_PS_ROOT_CONFIG_FILE not replaced
  .devtools/.phpstan_bootstrap.php
Labels: enhancement
