Repository friends-of-presta/fop_console, pull requests merged in 2021-07, with the labels that each got.

#132 Add command to manage categories
  .devtools/phpstan/stubs/Category.stub
  config/services.yml
  phpstan.neon.dist
  src/Commands/Categories/CleanCategory.php
Labels: feature

#144 phpstan level 5 ...
  .devtools/phpstan_baseline.neon
  src/Commands/Images/GenerateAbstract.php
  src/Commands/ShopStatus.php
Labels: enhancement

#152 Add contributor
  CONTRIBUTORS.md
Labels: documentation

#153 Add php 7.4 support
  README.md
Labels: documentation

#125 Manage non-essential modules
  README.md
  config/services.yml
  src/Commands/Modules/NonEssentialModules.php
Labels: feature
