Repository friends-of-presta/fop_console, pull requests merged in 2022-05, with the labels that each got.

#239 New command to scaffold a module: fop:module:generate
  .gitignore
  composer.json
  composer.lock
  config/services.yml
  src/Commands/Module/ModuleGenerate.php
  src/Resources/templates/generate_module_command/module/composer.json.twig
  src/Resources/templates/generate_module_command/module/controller/configuration.php.twig
  src/Resources/templates/generate_module_command/module/controller/form.php.twig
  src/Resources/templates/generate_module_command/module/controller/front_controller.php.twig
  src/Resources/templates/generate_module_command/module/controller/routes.yml.twig
  src/Resources/templates/generate_module_command/module/controller/services.yml
  src/Resources/templates/generate_module_command/module/controller/template_controller.twig
  src/Resources/templates/generate_module_command/module/main.php.twig
  src/Resources/templates/generate_module_command/module/test/bootstrap.php.twig
  src/Resources/templates/generate_module_command/module/test/phpunit.xml.twig
  src/Resources/templates/generate_module_command/module/views/js/front_controller.js.twig
Labels: feature

#241 update ps 1.7.8 to last version in tests
  .github/workflows/phpstan.yml
Labels: dev

#235 Add CategoryProductsCount command
  composer.json
  composer.lock
  config/services.yml
  src/Commands/Category/CategoryProductsCount.php
Labels: feature

#242 "opcache_invalidate" may not be defined if opcache extension is not installed
  src/Commands/Environment/EnvironmentDebug.php
Labels: bug

#233 Fix code quality tools
  .github/workflows/php-cs-fixer.yml
  .php_cs-fixer.dist.php
  composer.json
  composer.lock
  grumphp.yml.dist
  phpstan.neon.dist
  phpstan_baseline.neon
  src/Commands/Container/ContainerCheck.php
  src/Commands/Employee/EmployeeChangePassword.php
  src/Commands/Module/ModuleRename.php
  tests/Unit/PhpStanNamesConsistencyRuleTest.php
  tests/Validator/FOPCommandFormatsValidator.php
Labels: dev

#246 fix release notes - fix #174
  docs/RELEASE.md
Labels: dev

#247 Show configurations
  src/Commands/Configuration/ConfigurationExport.php
Labels: feature

#251 Add environment:get-parameters command
  config/services.yml
  src/Commands/Environment/EnvironmentGetParameters.php
Labels: feature
