Repository friends-of-presta/fop_console, pull requests merged in 2022-03, with the labels that each got.

#189 New Command Employee change password
  README.md
  config/services.yml
  src/Commands/Employee/EmployeeChangePassword.php
Labels: feature

#240 Contributing notes
  CONTRIBUTING.md
Labels: documentation

#172 Improve RenameModule command
  .github/workflows/php-cs-fixer.yml
  .github/workflows/phpunit.yml
  .gitignore
  .php_cs-fixer.dist.php
  phpstan.neon.dist
  src/Commands/Module/ModuleRename.php
  src/Tools/FindAndReplaceTool.php
  tests/Resources/csv/cased-replace-pairs/FOPModuleToRename-to-FOPModuleRenamed.csv
  tests/Resources/csv/cased-replace-pairs/Friends of Presta-to-Kaudaj.csv
  tests/Resources/csv/cased-replace-pairs/Kaudaj-to-Friends of Presta.csv
  tests/Resources/csv/cased-replace-pairs/search-replace.csv
  tests/Resources/csv/files-replace-pairs/kjmodulebedrock/found.csv
  tests/Resources/csv/files-replace-pairs/kjmodulebedrock/search-replace.csv
  tests/Resources/modules/README.md
  tests/Unit/CSVFileIterator.php
  tests/Unit/Tools/FindAndReplaceToolTest.php
Labels: enhancement, dev, hacktoberfest-accepted
